datasets:
  credit_risk:
    column_mapping:
      categorical_features:
        - 'checking_status'
        - 'credit_history'
        - 'purpose'
        - 'savings_status'
        - 'employment'
        - 'personal_status'
        - 'other_parties'
        - 'property_magnitude'
        - 'age'
        - 'other_payment_plans'
        - 'housing'
        - 'job'
        - 'own_telephone'
        - 'foreign_worker'
        - 'target'
      numerical_features:
        - 'duration'
        - 'credit_amount'
        - 'installment_commitment'
        - 'residence_since'
        - 'age'
        - 'existing_credits'
        - 'num_dependents'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/reference/reference1.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5